import os

TOKEN = os.getenv("TOKEN")
ADMIN_ID = int(os.getenv("ADMIN_ID", "0"))

BINANCE_API_KEY = os.getenv("BINANCE_API_KEY", "")
BINANCE_API_SECRET = os.getenv("BINANCE_API_SECRET", "")
BINANCE_WALLET_ADDRESS = os.getenv("BINANCE_WALLET_ADDRESS", "")
BINANCE_NETWORK = os.getenv("BINANCE_NETWORK", "BEP-20")

BINANCE_PAY_ID = os.getenv("BINANCE_PAY_ID", BINANCE_WALLET_ADDRESS)
